### ISSUE TITLE
Fedora: "The Prolog executable was not found"

### ISSUE THREAD

**Issue by mbuet2ner** [arthwang/vsc-prolog#13]
Thank you very much for your incredible work! Unfortunately, I can not get it to run properly on my system (Fedora 28).
I installed SWI Prolog 7.6.4 with `sudo dnf install pl` and double checked the executable path with `which swipl`, which returns `/usr/bin/swipl`. I have not changed the standard configuration. 
Still, I get the error 

> Cannot lint the prolog file. The Prolog executable was not found. Use the 'prolog.executablePath' setting to configure

**Comment by rmit-s3629862-Chenglong-Ma** [comment]
I have the same issue while my OS is Win 10.

**Comment by manumaso** [comment]
I have the same issue on Linux Mint 19, any solution?

**Comment by AlessioAtroni** [comment]
Having the same issue on macOS 10.13.6, SWI-Prolog 7.7.18, any solution?
@arthwang

**Comment by sacharias** [comment]
@AlessioAtroni I installed SWI-Prolog with Homebrew and had the same problem. Change the executablePath in vscode settings to this worked for me:
```json
"prolog.executablePath": "/usr/local/Cellar/swi-prolog/7.6.4/bin/swipl"
```

**Comment by AlessioAtroni** [comment]
Still not working, maybe the problem could be SWI-Prolog 7.7.18?

**Comment by AlessioAtroni** [comment]
# Debug

I debugged the extension, here is the stack trace, hope this helps (@arthwang):

```
/Applications/Visual Studio Code.app/Contents/MacOS/Electron --debugBrkPluginHost=40969 --debugId=dce5f3d9-4234-4a29-a072-be8c93a302ee --extensionDevelopmentPath=/Users/atro/Downloads/vsc-prolog-master 

Activating extension `arthurwang.vsc-prolog` failed:  Cannot find module '/Users/atro/Downloads/vsc-prolog-master/out/src/extension'
extensionHostProcess.js:459
Here is the error stack:  Error: Cannot find module '/Users/atro/Downloads/vsc-prolog-master/out/src/extension'
extensionHostProcess.js:459
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:831:951)
	at Function.t.getExtensionPathIndex.then.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:781:881)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:30:770)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:807:367
	at t._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:807:479)
	at t._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:806:337)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:804:204)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:459:497)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:459:116
	at Array.map (<anonymous>)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:459:91)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:457:367)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:804:646
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:971)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:559)
	at e.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:113:375)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:804:242
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:97
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:559)
	at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:1011)
	at n.Class.derive.join.i.forEach.$.then.o.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:205)
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:971)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:559)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:117:1020
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:150:661
	at LOOP (original-fs.js:1757:14)
	at _combinedTickCallback (internal/process/next_tick.js:131:7)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by colingoldberg** [comment]
I installed VSC Prolog - which looks great - on my mac, but I am confused about where to add the executable path configuration. I don't see any existing launch.json file in the .vscode directory (in my home directory).

In ~/.vscode/extensions/arthurwang.vsc-prolog-0.8.23/, I have:
-rw-r--r--   1 ...  staff   2967 Feb 12 11:31 CHANGELOG.md
-rw-r--r--   1 ...  staff   1078 Feb 12 11:31 LICENSE.txt
-rw-r--r--   1 ...  staff  19983 Feb 12 11:31 README.md
drwxr-xr-x  27 ...  staff    864 Feb 12 11:31 images
drwxr-xr-x  25 ...  staff    800 Feb 12 11:31 node_modules
drwxr-xr-x   3 ...  staff     96 Feb 12 11:31 out
-rwxr-xr-x   1 ...  staff   8390 Feb 12 11:31 package.json
-rwxr-xr-x   1 ...  staff    444 Feb 12 11:31 prolog.configuration.json
drwxr-xr-x   5 ...  staff    160 Feb 12 11:31 snippets
drwxr-xr-x   5 ...  staff    160 Feb 12 11:31 syntaxes

Should I create launch.json here and add "prolog.executablePath" to it?

**Comment by marcoswmv** [comment]
> @AlessioAtroni I installed SWI-Prolog with Homebrew and had the same problem. Change the executablePath in vscode settings to this worked for me:
> 
> ```json
> "prolog.executablePath": "/usr/local/Cellar/swi-prolog/7.6.4/bin/swipl"
> ```

Thank you! It worked for me!
I am on MacOS Mojave using vs code
And tried this path to my executable as i am using it through terminal
> /usr/local/Cellar/gnu-prolog/1.4.5/bin/gprolog

**Comment by nijatmursali** [comment]
> @AlessioAtroni I installed SWI-Prolog with Homebrew and had the same problem. Change the executablePath in vscode settings to this worked for me:
> 
> ```json
> "prolog.executablePath": "/usr/local/Cellar/swi-prolog/7.6.4/bin/swipl"
> ```

It worked for me as well, but why it opens new windows when you change something in .pl file?

**Comment by potatosenior** [comment]
> > @AlessioAtroni I installed SWI-Prolog with Homebrew and had the same problem. Change the executablePath in vscode settings to this worked for me:
> > ```json
> > "prolog.executablePath": "/usr/local/Cellar/swi-prolog/7.6.4/bin/swipl"
> > ```
> 
> It worked for me as well, but why it opens new windows when you change something in .pl file?

edit: found the problem, i was using "swipl-win.exe" instead of "swipl.exe"

**Comment by sballari** [comment]
> Edit: The solution is download de .deb from the official page of visual studio code, not from the software center.

Is this still the only solution available for repo users (snap,apt,dfn,yum, etc...)?
