### ISSUE TITLE
Prolog terminal won't open in integrated terminal

### ISSUE THREAD

**Issue by NickyLogan** [arthwang/vsc-prolog#3]
The terminal opens in a new window instead opening inside the integrated terminal
  
here is the traceback
~~~
TypeError: Cannot read property 'text' of undefined
	at vscode_1.workspace.onDidChangeTextDocument.e (C:\Users\Nicky\.vscode\extensions\arthurwang.vsc-prolog-0.8.7\out\src\features\editHelpers.js:120:34)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:218)
	at e.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:432:782)
	at e.$acceptModelSaved (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:432:565)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:516:87)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:580)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:270)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:356:206
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:358:204
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:988
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:218)
	at Socket.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:135:717)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ workbench.main.js:sourcemap:4056
workbench.main.js:sourcemap:249 [Extension Host] (node:9020) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.main.js:sourcemap:249
t._logExtensionHostMessage @ workbench.main.js:sourcemap:2573
(anonymous) @ workbench.main.js:sourcemap:2569
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
~~~

**Comment by arthwang** [comment]
Thank you for your reporting issues. But I can't reproduce the issue. The trace information you provided seems to have nothing to do with 'opening terminal'. 
Would you please to provide detailed environments and steps to reproduce it. 
In windows, swipl executable 'swipl-win.exe' opens swipl in new window. If this is what happens to you just set the prolog.executablePath to refer to 'swipl.exe', as such: "c:/Program Files/swipl/bin/swipl.exe".
Happy coding!

**Comment by NickyLogan** [comment]
Ah, thank you so much. It is fixed now.

Thanks for the amazing plugin!
